[1m[31mERROR   [0m root:test_data_validation.py:78 Nulls found:{'dob': 1}